"""wiki.py — Generate an Obsidian-compatible wiki vault from CodeDNA annotations.

exports: SKIP_DIRS | build_wiki_vault(repo_root, out_dir, extensions) | _wikilink(rel) | _slug_for_rel(rel) | _extract_fields(path) | _page_markdown(rel, fields) | _generate_index(repo_root, out_dir, rel_paths) | _generate_log(repo_root, out_dir) | _read_project_name(repo_root) | _list_top_level_dirs(repo_root) | render_project_wiki(project_name, repo_root) | build_project_wiki(repo_root, out_path) | _escape_obsidian_hashtags(text)
used_by: codedna_tool/cli.py → build_wiki_vault (wiki subcommand)
wiki:    docs/wiki/wiki.md
rules:   The output vault is an artifact — rigenerato ad ogni `codedna wiki bootstrap`.
         Preserve the content BELOW the '<!-- AGENT NOTES' marker on re-runs (agent-authored).
         Every [[wikilink]] must resolve to an existing .md file inside the vault, else the Obsidian
         graph won't connect — so wikilink slugs MUST be deterministic from the source rel path.
         Do NOT parse YAML — use regex/line parsing like cli.py does.
agent:   claude-opus-4-6 | anthropic | 2026-04-21 | s_20260421_wiki | initial wiki vault generator — Python docstring + non-Python lang header → markdown page with [[wikilinks]] from used_by/related; preserves AGENT NOTES section across re-runs
claude-opus-4-6 | anthropic | 2026-04-21 | s_20260421_wiki2 | add render_project_wiki + build_project_wiki (narrative wiki, 7-section template adapted from @workingfm PR #2); strip sub-agent/skill scaffolding in favor of hook-based enforcement
claude-opus-4-6 | anthropic | 2026-04-21 | s_20260421_wiki3 | fix Obsidian graph pollution — wrap numeric hashtags (e.g. `#1072-1077`) in backticks via _escape_obsidian_hashtags so they render as inline code, not tag nodes
claude-opus-4-6 | anthropic | 2026-04-21 | s_20260421_wiki4 | switch vault to nested layout — `_slug_for_rel` preserves folder hierarchy; wikilinks use "relative path to file" format; handles duplicate basenames (e.g. __init__.py)
"""

from __future__ import annotations

import ast
import re
from datetime import date
from pathlib import Path

SKIP_DIRS = {
    "__pycache__", ".git", "venv", ".venv", "node_modules", "dist", "build",
    "migrations", "_repo_cache", "runs", ".pytest_cache", ".mypy_cache",
    ".ruff_cache", "docs", "paper", "thesis", "dev_notes", "examples",
    "worktrees", ".claude",
    # Benchmark fixtures — annotated but NOT part of this project's source
    "projects_swebench", "projects",
}

_AGENT_NOTES_MARKER = "<!-- AGENT NOTES · edits below survive codedna wiki refresh -->"
_AUTO_HEADER = "<!-- AUTO-GENERATED by codedna wiki · edits above AGENT NOTES will be overwritten -->"


def _wikilink(rel: str) -> str:
    """Convert a repo-relative path to an Obsidian-safe wikilink (nested vault form).

    Rules:   Uses Obsidian's "relative path to file" wikilink format, which keeps
             the folder hierarchy visible while disambiguating duplicate basenames
             (e.g. multiple __init__.py files in different packages).
             Return format: [[folder/subfolder/name|display]] — strip the file extension
             so the link resolves to the corresponding .md page in the vault.
    """
    clean = rel.strip()
    if "→" in clean or "—" in clean:
        # Caller passed a raw used_by/related entry — extract the path part
        for sep in ("→", "—"):
            if sep in clean:
                clean = clean.split(sep, 1)[0].strip()
                break
    target = _slug_for_rel(clean)
    return f"[[{target}|{clean}]]"


def _slug_for_rel(rel: str) -> str:
    """Return the vault-relative wikilink target (without .md) for a source rel path.

    Rules:   Strip the source extension so 'foo/bar.py' → 'foo/bar' — Obsidian
             auto-appends .md. Preserves folder hierarchy for nested vault layout.
    """
    path = Path(rel)
    # Drop the primary extension. Compound extensions (.blade.php) collapse fully.
    if rel.endswith(".blade.php"):
        stem = rel[: -len(".blade.php")]
    else:
        stem = str(path.with_suffix(""))
    return stem


def _extract_fields(path: Path) -> dict | None:
    """Extract CodeDNA field dict from a Python or non-Python source file.

    Rules:   Returns None if the file has no CodeDNA header.
             Must never raise — catch and return None on any parse error.
             Python uses AST to find the docstring; non-Python uses language adapter prefix.
    """
    from codedna_tool.cli import _parse_existing_docstring, _parse_lang_header
    from codedna_tool.languages import get_adapter

    try:
        source = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None

    if path.suffix == ".py":
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return None
        docstring = ast.get_docstring(tree, clean=False)
        if docstring is None:
            return None
        # _parse_existing_docstring expects the triple-quoted form
        return _parse_existing_docstring(f'"""{docstring}"""')

    # Non-Python: look up an adapter for the extension
    name = path.name.lower()
    if name.endswith(".blade.php"):
        ext = ".blade.php"
    else:
        ext = path.suffix.lower()
    adapter = None
    try:
        adapter = get_adapter(ext)
    except Exception:
        return None
    if adapter is None:
        return None
    prefix = getattr(adapter, "comment_prefix", "//")
    return _parse_lang_header(source, prefix)


def _field_value(fields: dict, key: str) -> str:
    """Return the cleaned value of a field (strip '<key>:' prefix and whitespace)."""
    raw = fields.get(key, "")
    if not raw:
        return ""
    prefix = f"{key}:"
    if raw.startswith(prefix):
        raw = raw[len(prefix):]
    return raw.strip()


_HASHTAG_NUMBER_RE = re.compile(r"#\d[\d-]*")


def _escape_obsidian_hashtags(text: str) -> str:
    """Wrap #123, #123-456 in backticks so Obsidian doesn't treat them as tags.

    Rules:   Obsidian parses `#<digits>` as a tag → spurious graph nodes.
             We want those numbers rendered as plain text (issue / CodeQL refs).
             Only numeric hashtags are touched — alphabetic tags like #feature stay untouched.
    """
    return _HASHTAG_NUMBER_RE.sub(lambda m: f"`{m.group(0)}`", text)


def _render_bullets(entries: list[str]) -> list[str]:
    """Render a list of entries as Markdown bullets, skipping blanks."""
    out = []
    for e in entries:
        e = e.strip()
        if e:
            out.append(f"- {e}")
    return out


def _page_markdown(rel: str, fields: dict) -> str:
    """Render a markdown wiki page from CodeDNA fields.

    Rules:   Layout MUST be stable — agents rely on section positions for merges.
             Always end with the _AGENT_NOTES_MARKER so re-runs can preserve content below it.
             used_by/related paths become [[wikilink|display]] Obsidian links.
    """
    lines: list[str] = [
        _AUTO_HEADER,
        "",
        f"# {rel}",
        "",
    ]

    first_line = fields.get("first_line", "").strip().lstrip('"').strip()
    if first_line and first_line != rel:
        lines.append(f"> {first_line}")
        lines.append("")

    exports = _field_value(fields, "exports")
    if exports and exports != "none":
        lines.append("## Exports")
        lines.append("")
        for item in [x.strip() for x in exports.split("|")]:
            if item:
                lines.append(f"- `{item}`")
        lines.append("")

    used_by = _field_value(fields, "used_by")
    if used_by and used_by != "none":
        lines.append("## Used by")
        lines.append("")
        for entry in used_by.split("\n"):
            entry = entry.strip()
            if not entry:
                continue
            if "→" in entry:
                p, sym = entry.split("→", 1)
                lines.append(f"- {_wikilink(p.strip())} → {sym.strip()}")
            else:
                lines.append(f"- {_wikilink(entry)}")
        lines.append("")

    related = _field_value(fields, "related")
    if related:
        lines.append("## Related")
        lines.append("")
        for entry in related.split("\n"):
            entry = entry.strip()
            if not entry:
                continue
            if "—" in entry:
                p, note = entry.split("—", 1)
                lines.append(f"- {_wikilink(p.strip())} — {note.strip()}")
            else:
                lines.append(f"- {_wikilink(entry)}")
        lines.append("")

    rules = _field_value(fields, "rules")
    if rules and rules != "none":
        lines.append("## Rules")
        lines.append("")
        for r in rules.split("\n"):
            r = r.strip()
            if r:
                lines.append(f"- {_escape_obsidian_hashtags(r)}")
        lines.append("")

    agent = _field_value(fields, "agent")
    if agent:
        # Filter: only lines that look like an agent entry (contain |, the standard separator).
        # This drops trailing usage/explanatory prose that the parser folds into agent: by accident.
        agent_entries = [e.strip() for e in agent.split("\n") if "|" in e.strip()]
        if agent_entries:
            lines.append("## Agent history")
            lines.append("")
            for entry in agent_entries:
                lines.append(f"- {_escape_obsidian_hashtags(entry)}")
            lines.append("")

    message = _field_value(fields, "message")
    if message:
        lines.append("## Open messages")
        lines.append("")
        lines.append(f"> {message}")
        lines.append("")

    lines.append(_AGENT_NOTES_MARKER)
    lines.append("")
    return "\n".join(lines)


def _preserve_agent_notes(existing_text: str) -> str:
    """Extract the AGENT NOTES section from an existing page to carry it forward.

    Rules:   Returns the text starting from the _AGENT_NOTES_MARKER, or '' if absent.
             If multiple markers are present, only the first is recognized (should never happen).
    """
    idx = existing_text.find(_AGENT_NOTES_MARKER)
    if idx < 0:
        return ""
    return existing_text[idx:]


def _generate_index(repo_root: Path, out_dir: Path, rel_paths: list[str]) -> None:
    """Generate vault/README.md with a tree-style index of all pages.

    Rules:   Group by top-level directory for readability.
             Each entry is a [[wikilink|display]] so Obsidian graph gets full connectivity.
    """
    lines = [
        _AUTO_HEADER,
        "",
        f"# {repo_root.name} — CodeDNA Wiki",
        "",
        "Auto-generated from CodeDNA annotations. Open this directory in Obsidian to explore the graph.",
        "",
        f"**{len(rel_paths)} annotated files.**",
        "",
    ]

    # Group by top-level directory
    groups: dict[str, list[str]] = {}
    for rel in sorted(rel_paths):
        parts = rel.split("/")
        top = parts[0] if len(parts) > 1 else "(root)"
        groups.setdefault(top, []).append(rel)

    for top in sorted(groups.keys()):
        lines.append(f"## {top}")
        lines.append("")
        for rel in groups[top]:
            lines.append(f"- {_wikilink(rel)}")
        lines.append("")

    lines.append(_AGENT_NOTES_MARKER)
    lines.append("")
    (out_dir / "README.md").write_text("\n".join(lines), encoding="utf-8")


def _generate_log(repo_root: Path, out_dir: Path) -> None:
    """Generate vault/log.md from .codedna agent_sessions: (append-only).

    Rules:   Reads .codedna and emits one section per session in chronological order.
             Missing .codedna → emit a minimal placeholder so Obsidian still shows the page.
    """
    codedna_path = repo_root / ".codedna"
    lines = [
        _AUTO_HEADER,
        "",
        "# Session log",
        "",
        "Chronological log of agent sessions from `.codedna`.",
        "",
    ]

    if not codedna_path.exists():
        lines.append("_No `.codedna` manifest found._")
        lines.append("")
    else:
        try:
            text = codedna_path.read_text(encoding="utf-8", errors="replace")
            lines.append("```yaml")
            lines.append(text.rstrip())
            lines.append("```")
            lines.append("")
        except OSError:
            lines.append("_Could not read `.codedna`._")
            lines.append("")

    lines.append(_AGENT_NOTES_MARKER)
    lines.append("")
    (out_dir / "log.md").write_text("\n".join(lines), encoding="utf-8")


def build_wiki_vault(repo_root: Path, out_dir: Path,
                     extensions: list[str] | None = None) -> int:
    """Generate an Obsidian-compatible wiki vault from all CodeDNA-annotated files.

    Rules:   Returns the number of pages written (excluding index/log).
             Preserves AGENT NOTES sections when re-running over an existing vault.
             Skips files without CodeDNA headers silently — wiki is opt-in via init/refresh.
             extensions defaults to every file that has an annotation; pass ['.py'] to limit.
    """
    if extensions is not None:
        extensions_set = {e if e.startswith(".") else f".{e}" for e in extensions}
    else:
        extensions_set = None

    out_dir.mkdir(parents=True, exist_ok=True)
    rel_paths: list[str] = []

    for f in sorted(repo_root.rglob("*")):
        if not f.is_file():
            continue
        if any(part in SKIP_DIRS for part in f.parts):
            continue
        if extensions_set is not None and f.suffix not in extensions_set:
            continue

        fields = _extract_fields(f)
        if not fields:
            continue

        try:
            rel = str(f.relative_to(repo_root))
        except ValueError:
            # File outside repo_root — skip
            continue

        # Nested vault — mirror the source hierarchy. Obsidian "relative path to file"
        # link format handles duplicate basenames (e.g. __init__.py) cleanly.
        out_path = out_dir / f"{_slug_for_rel(rel)}.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)

        # Preserve any AGENT NOTES from previous run
        preserved_notes = ""
        if out_path.exists():
            try:
                existing_text = out_path.read_text(encoding="utf-8")
                preserved_notes = _preserve_agent_notes(existing_text)
            except OSError:
                preserved_notes = ""

        page = _page_markdown(rel, fields)
        if preserved_notes:
            # Splice preserved notes back in place of the empty marker section
            page = page.split(_AGENT_NOTES_MARKER)[0] + preserved_notes

        out_path.write_text(page, encoding="utf-8")
        rel_paths.append(rel)

    _generate_index(repo_root, out_dir, rel_paths)
    _generate_log(repo_root, out_dir)

    return len(rel_paths)


# ── Project-level semantic wiki (narrative overview) ─────────────────────────
# Originally contributed by @workingfm in PR #2. Rewritten to:
#  - Emit to docs/codedna-wiki.md (not repo root — v0.9 convention keeps docs/ clean)
#  - Work WITHOUT scaffolding skill files or sub-agents (we enforce via hooks instead)
#  - Preserve an AGENT NOTES section so curated additions survive regeneration

_PROJECT_WIKI_MARKER_AGENT = "<!-- AGENT NOTES · edits below survive `codedna wiki sync` -->"
_PROJECT_WIKI_MARKER_AUTO = (
    "<!-- AUTO-GENERATED by `codedna wiki sync` · "
    "edits ABOVE the AGENT NOTES marker will be overwritten -->\n"
    "<!-- Template originally contributed by @workingfm in PR #2 — "
    "adapted for hook-based refresh. -->"
)


def _read_project_name(repo_root: Path) -> str:
    """Extract project: from .codedna or fall back to the directory name.

    Rules:   Must never raise — unreadable .codedna returns dir name silently.
    """
    codedna = repo_root / ".codedna"
    if codedna.exists():
        try:
            text = codedna.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        m = re.search(r"^project:\s*\"?(.+?)\"?\s*$", text, re.MULTILINE)
        if m:
            return m.group(1).strip()
    return repo_root.name


def _list_top_level_dirs(repo_root: Path, limit: int = 8) -> list[str]:
    """List up to `limit` stable top-level directories for the topology section.

    Rules:   Filter SKIP_DIRS + hidden dirs — we want meaningful product/research subsystems.
    """
    skip = SKIP_DIRS
    out: list[str] = []
    try:
        for child in sorted(repo_root.iterdir()):
            if not child.is_dir():
                continue
            if child.name.startswith(".") or child.name in skip:
                continue
            out.append(child.name)
    except OSError:
        return out
    return out[:limit]


def render_project_wiki(project_name: str, repo_root: Path) -> str:
    """Render the narrative project wiki (docs/codedna-wiki.md content).

    Rules:   Structure follows @workingfm's 7-section template (Identity → How this relates to L0
             → Semantic topology → Operational workflows → Testing → Hotspots → Refresh protocol).
             Paths are relative to docs/ (so .codedna → ../.codedna, codedna_tool/ → ../codedna_tool/).
             MUST end with _PROJECT_WIKI_MARKER_AGENT so sync can preserve curated notes.
    """
    dirs = _list_top_level_dirs(repo_root)
    topology = "\n".join(f"- `{name}/`" for name in dirs) or "- Add major subsystem directories here"
    today = date.today().isoformat()

    return f"""{_PROJECT_WIKI_MARKER_AUTO}

# {project_name} — CodeDNA Wiki

Last refreshed: {today}
Primary structural source: [.codedna](../.codedna)
Per-file Obsidian vault: [docs/wiki/](wiki/)

## Identity

`{project_name}` uses CodeDNA as its in-source coordination protocol.

This file is the **semantic companion** to `.codedna`:

- `.codedna` is Level 0 structural truth (packages, session log, boundaries)
- `docs/codedna-wiki.md` (this file) is the semantic map agents use to preserve architectural understanding over time

## How this wiki relates to L0

Use `.codedna` for:

- project/package structure
- key files
- recent session log

Use this wiki for:

- architecture mental model
- workflows
- hotspots and drift
- contradictions or open questions

If this file disagrees with `.codedna`, refresh this file and trust `.codedna` first.

## Semantic topology

Starter top-level view:

{topology}

Fill each entry with the role it plays — what the subsystem is for, how the boundaries work,
and where agents should start reading.

## Operational workflows

- **Setup** — `codedna install` wires CLAUDE.md / AGENTS.md, optional pre-commit hook, starter `.codedna`
- **Annotate** — `codedna init` writes L1/L2 headers; `codedna update` fills in missing ones
- **Maintain** — `codedna refresh` repairs structural drift; `codedna check` measures coverage
- **Wiki (v0.9 experimental)** — `codedna wiki sync` rewrites this file; `codedna wiki bootstrap` emits the per-file vault under `docs/wiki/`

## Testing and validation model

Document what the project's test suite actually guarantees (idempotency, coverage, adapter regressions)
and what it does NOT cover yet. This is the place to flag "we don't test X yet" for future agents.

## Hotspots and likely drift

Document:

- monolithic files prone to scope creep
- fragile integrations (remote template fetches, environment-specific paths)
- generated/vendor areas agents should avoid
- places where structure and intent diverge

## Refresh protocol

Refresh this file when:

- `.codedna` changes meaningfully
- major refactors land
- new subsystems or workflows appear

The post-commit hook runs `codedna wiki sync` automatically — a maintainer can always
re-run it manually.

{_PROJECT_WIKI_MARKER_AGENT}
"""


def build_project_wiki(repo_root: Path, out_path: Path) -> Path:
    """Write docs/codedna-wiki.md preserving any existing AGENT NOTES section.

    Rules:   If out_path exists, the block from _PROJECT_WIKI_MARKER_AGENT onward is carried forward.
             Else the default empty AGENT NOTES trailer is emitted.
             Returns the path written (for caller convenience).
    """
    project_name = _read_project_name(repo_root)
    page = render_project_wiki(project_name, repo_root)

    if out_path.exists():
        try:
            existing = out_path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
        idx = existing.find(_PROJECT_WIKI_MARKER_AGENT)
        if idx >= 0:
            preserved = existing[idx:]
            page = page.split(_PROJECT_WIKI_MARKER_AGENT)[0] + preserved

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(page, encoding="utf-8")
    return out_path
